version: '3'

services:
        diff_priv_server:
                build:
                        context: .
                        dockerfile: DiffPrivServer_Dockerfile
                image: diff_priv_server
                hostname: diff_priv_server
                volumes:
                  - /var/lib/docker/volumes/diffpriv_server/csv_files/:/diffpriv/csv_files/
                  - /var/lib/docker/volumes/diffpriv_server/logs/:/diffpriv/logs/
                  - /var/lib/docker/volumes/diffpriv_server/users/:/diffpriv/users/
                networks:
                        coprotect_network:
                                ipv4_address: 172.25.0.2

networks:
        coprotect_network:
                driver: bridge
                ipam:
                        config:
                                - subnet: 172.25.0.0/16
